callstack/reassure

- .changeset/plenty-beds-greet.md
- README.md
- packages/reassure-cli/src/commands/measure.ts
- packages/reassure/README.md
- Added **TEST_RUNNER_PATH** and **TEST_RUNNER_ARGS** env variables to handle runner configuration for the measure script.
- Updated the Readme file.
Related to #70
> fix: add `TEST_RUNNER_PATH` and `TEST_RUNNER_ARGS` env variables to configure test runner

- packages/reassure-measure/src/config.ts
Step two of web React/RTL support. Auto-discovery of RTL `render` and `cleanup. 
All tests pass.
This code should be enough to support React web/RTL in projects. I've got a separate branch with Vite-based React boilerplate correctly running Reassure.
> feature: RTL autodiscovery

- .changeset/ten-ducks-remain.md
- README.md
- examples/native/jest.config.js
- examples/native/jestSetup.js
- packages/reassure-measure/src/config.ts
- packages/reassure-measure/src/measure.tsx
- packages/reassure-measure/src/testingLibrary.ts
`testingLibrary: 'react-native' | 'react' | { render, cleanup }` configuration option. Also logging errors, warnings and messages in order to help users figure out potential issues with that option.
All checks & test pass.
> Add `testingLibrary` config option

- README.md
- examples/native/reassure-tests.sh
- packages/reassure/README.md
Add `yarn install` + `yarn turbo run build` to `reassure-tests.sh` script in `examples/native` so that baseline version is using relevant deps from monorepo. Also updated docs to suggest using `yarn install` in normal cases.
All checks and tests pass.
> feature: add yarn install to reassure-tests.sh

- .github/workflows/main.yml
CI build started failing during `yarn turbo run build` step:
```
@callstack/reassure-measure:build: ✔ Wrote definition files to lib/typescript
@callstack/reassure-compare:build: ✔ Wrote definition files to lib/typescript
@callstack/reassure-cli:build: cache miss, executing 24570b2370bb2be9
@callstack/reassure-cli:build: $ bob build
@callstack/reassure-cli:build: /bin/sh: 1: bob: not found
@callstack/reassure-cli:build: error Command failed with exit code 127.
@callstack/reassure-cli:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@callstack/reassure-cli:build: ERROR: command finished with error: command (packages/reassure-cli) yarn run build exited (127)
command (packages/reassure-cli) yarn run build exited (127)
```
Looks like deps caching …
> fix: CI build that throw 'bob not found'

- examples/native-expo/jest-setup.js
- examples/native-expo/jest.config.js
- examples/native-expo/jest.config.json
- examples/native-expo/package.json
- examples/native-expo/reassure-tests.sh
- examples/native-expo/yarn.lock
Update expo example to use Expo 46, React 18, React Native 0.69, RNTL 11.
All checks and tests pass.
> chore: upgrade expo example deps

- examples/native-expo/src/SlowList.perf-test.tsx
- examples/native/package.json
- examples/native/src/OtherTest.perf-test.tsx
- examples/native/src/SlowList.perf-test.tsx
- yarn.lock
There seems to be an issue with `TouchableOpacity` implementation from React Native that causes the random increase in render counts. Swapping `TouchableOpacity` for `Pressable` reduces the renders down again.
I've did some additional testing and it appears that the issue affects only `TouchableOpacity`, other `TouchableXxx` work fine:
- `TouchableHighlight`
- `TouchableNativeFeedback`
- `TouchableWithoutFeedback`
All checks pass.
> refactor: replace TouchableOpacity by Pressable

- .changeset/silver-roses-sneeze.md
- packages/reassure-cli/src/commands/measure.ts
Use the exit code from the jest spawned process to fail the reassure job if jest errors out. Our performance tests were silently failing since jest was failing to properly render the components. See https://github.com/callstack/reassure/issues/171
I tested locally by manually throwing an error in a test and running reassure.
> Fail the CI measure process if jest fails

- examples/native-expo/jest.config.js
- examples/native/jest.config.js
- examples/native/package.json
Resolves #189 by removing unnecessary jest `setupFilesAfterEnv` of `@testing-library/jest-native/extend-expect`, which occurred if user did not run `yarn install` in the top level folder, as the `examples/native-expo` did not have dependency on `@testing-library/jest-native` itself.
All checks pass.
> fix: remove unnecessary jest-native deps

- README.md
- examples/native-expo/reassure-tests.sh
- examples/native/reassure-tests.sh
- examples/web-vite/reassure-tests.sh
- packages/reassure-compare/src/types.ts
- packages/reassure-compare/src/utils/format.ts
- packages/reassure/README.md
`git switch main` run as part of `reassure-tests.sh` silently fails, as local git is has not been fetched from original
Analyse GH actions logs to confirm that the test is passing.
> fix: git switch on CI

- .changeset/metal-laws-knock.md
- packages/reassure-cli/src/commands/measure.ts
`TEST_RUNNER_PATH` was not applied due to incorrect usage of operator priorities.  
Resolves #324 
All checks run correctly.
> fix: TEST_RUNNER_PATH not being applied

- README.md
- docusaurus/docs/installation.md
- packages/reassure-cli/src/commands/measure.ts
Resolves: https://github.com/callstack/reassure/issues/314
- Added new option to `yarn reassure measure` and subsequently - `yarn reassure` commands: `--file | -f`
- Added validation for the option by checking whether provided file exists
- Fallback to default if file does not exist
**Important**
Using `TEST_RUNNER_ARGS` will override this feature as it works by adjusting the `defaultArgs` string
1. Clone repo
2. run `yarn`
3. run `yarn reassure -f "examples/native/src/OtherTest.perf-test.tsx"`
Result: Only one test is ran
https://user-images.githubusercontent.com/18323849/217242592-9d221c06-944c-45f9-bbcf-accdd63a7589.mov
> Added support for passing a custom `--testMatch` option to Jest

- examples/native-expo/dangerfile.js
- examples/native-expo/package.json
- examples/native-expo/yarn.lock
- examples/web-nextjs/dangerfile.js
- examples/web-nextjs/package.json
- examples/web-nextjs/reassure-tests.sh
- examples/web-nextjs/yarn.lock
- examples/web-vite/.gitignore
- examples/web-vite/dangerfile.js
- examples/web-vite/package.json
- examples/web-vite/yarn.lock
Run `reassure init` in the examples apps and add missing files like `dangerfile.js`, `reassure-tests.sh`, etc
Based on input from #385 
Local tests in examples should pass.
> chore: add dangerfiles to examples

- .changeset/sharp-singers-judge.md
- packages/reassure-cli/src/commands/measure.ts
This PR fixes issues with Jest Expo package by finding the real Jest binary instead of using `jest` which is replaced by Jest Expo.
All checks should pass.
> fix: jest-expo path

- .changeset/ninety-pants-perform.md
- README.md
- docusaurus/docs/api.md
- packages/reassure-measure/src/__tests__/measure.test.tsx
- packages/reassure-measure/src/measure.tsx
- packages/reassure/README.md
This PR excludes wrapper component passed using `wrapper` option to `measureRender`/`measurePerformance` from being included in the render stats.
Added test to detect wrapper render.
> fix: measureRender should exclude wrapper render durations

- .changeset/stupid-suits-learn.md
- README.md
- docusaurus/docs/api.md
- packages/reassure-measure/src/__tests__/measure.test.tsx
- packages/reassure-measure/src/measure.tsx
- packages/reassure/README.md
Currently the `wrapper` option accepts a wrapping function: 
```
(node: React.ReactElement) => JSX.Element;
```
However, both RNTL and RTL accept a wrapper component type:
```
wrapper?: React.ComponentType<any>;
```
Each approach can be relatively easy transformed to the other one, but having slightly different wrapper types make adapting tests from RNTL, RTL slightly more cumbersome.
This is a breaking change, but since we are pre 1.0 version it should result in minor version change (probably 0.9.0).
Added test that checks if the wrapper is placed in the proper place in the element tree.
> (BREAKING) feat: make wrapper option compatible with RTL/RNTL

- .changeset/purple-pumas-love.md
- packages/reassure-logger/src/logger.ts
Running reassure got the error on `node:readline`
Removing the `node:` prefix worked
> fix: removed "node:" prefix from logger readline

- packages/reassure-compare/src/compare.ts
- packages/reassure-compare/src/output/console.ts
Found a minor typo while setting up Reassurance.
- Run a test
- Read the logs
Before:
> fix: Correct minor typos in log output

- .changeset/funny-pandas-repeat.md
- packages/reassure/src/index.ts
This PR fixes lack of the `measureFunction` function in the public API.
Put `import {measureFunction} from 'reassure';` in your test file.
> hotfix: make measureFunction a public API

- .changeset/nasty-cars-attack.md
- docusaurus/docs/troubleshooting.md
- packages/reassure-cli/src/commands/check-stability.ts
- packages/reassure-cli/src/commands/measure.ts
This PR adds support for Reassure `--enable-wasm` option that would replace `--jitless` flag for `--no-opt --no-sparkplug` flags intended to disable Turbo Fan optimizing compiler and Sparkplug non-optimizing compiler in order to maintain execution time stability provided by JIT-less mode.
Resolves #426 
Resolves #421
> chore: enable WASM support

- packages/compare/src/output/markdown.ts
- packages/compare/src/utils/markdown.ts
Proper name form markdown `# XXX` is heading, not header. So I've rename the function names,
Tested visually in generated Danger report.
> refactor: rename `headerX` to `headingX` in markdown utils

- .changeset/yellow-months-smoke.md
- packages/measure/src/__tests__/measure-function.test.tsx
- packages/measure/src/__tests__/measure-renders.test.tsx
- packages/measure/src/measure-function.tsx
- packages/measure/src/measure-helpers.tsx
- packages/measure/src/measure-renders.tsx
- packages/measure/src/output.ts
- packages/measure/src/types.ts
Make public API more flexible in supporting multiple results per `measure*` call.
> refactor: future support for returning multiple results

- packages/compare/package.json
- packages/compare/src/utils/format.ts
- yarn.lock
Fix unescaped regex pattern (`.`)
> fix: iso date milliseconds regex

- package.json
- packages/cli/package.json
- packages/compare/package.json
- packages/danger/package.json
- packages/logger/package.json
- packages/measure/package.json
- packages/reassure/package.json
- test-apps/native/babel.config.js
- test-apps/native/package.json
- yarn.lock
> chore: pdate deps 2024-05-09

- docusaurus/docs/migration-v1.md
- packages/cli/src/commands/measure.ts
- packages/compare/src/compare.ts
- packages/compare/src/index.ts
- packages/compare/src/output/console.ts
- packages/compare/src/output/markdown.ts
- packages/compare/src/type-schemas.ts
- packages/compare/src/types.ts
- packages/compare/src/utils/format.ts
- packages/compare/src/utils/validate.ts
- packages/measure/src/index.ts
- packages/reassure/README.md
- packages/reassure/package.json
- packages/reassure/src/index.ts
- yarn.lock
Make `reassure` package export more useful types like: `PerformanceHeader`, `PerformanceEntry`, `CompareResult`, etc
> chore: export types

- package.json
- packages/cli/package.json
- packages/compare/package.json
- packages/danger/package.json
- packages/logger/package.json
- packages/measure/package.json
- packages/reassure/package.json
- turbo.json
- yarn.lock
> chore: clean scripts

- .changeset/six-rivers-impress.md
- packages/measure/src/testing-library.ts
I found out that the `testingLibrary` option provided in the config object is not respected in the `getTestingLibrary` function. The function returns 'react-native' no matter what we provide in the configuration.
Looks like the early return statement [accidentally removed or forgotten](https://github.com/callstack/reassure/pull/456/files#diff-9916cc417df3ae60098b0a61764572f50fdaa34c2a738c26eec6a820cc9dfdf5R87) during the v1 effort.
`measureRenderInternals` function relies on `getTestingLibrary` and [runs this code](https://github.com/callstack/reassure/blob/5f9127a1f8d257b08c1b67a9418d63e2a99a54eb/packages/measure/src/measure-renders.tsx#L89) for `react-native`.  It throws an error with `react` testing library, thus this tiny mistake makes `reassure` unusable with `react` testing library. …
> fix: respect to the "testingLibrary" config option

- .changeset/gentle-sloths-crash.md
- packages/cli/src/commands/measure.ts
Before:
* files ending in `*.perf-test.(js|jsx|ts|tsx)`
After:
* files ending in `*.perf-test.(js|jsx|ts|tsx)`
* files ending in `*.perf.(js|jsx|ts|tsx)`
* files in `__perf__` folder
Manual tests
> feat: extend default test match

- .changeset/tough-ants-shout.md
- packages/cli/src/commands/measure.ts
Resolves #294 
Resolves #510 
By providing easy option to forward flags to test runner (Jest by default): `yarn reassure -- --coverage=false`.
Manual testing.
> feat: pass test runner options

- README.md
- docusaurus/docs/api.md
- docusaurus/docs/migration-v1.md
- packages/reassure/README.md
Tweaks docs to reflect recent changes.
> docs: tweaks

- packages/cli/src/commands/measure.ts
Passing runner args through CLI doesn’t work, because it’s always passed as a string which is then spread to individual characters. Bug introduced in #511.
Pass custom config through the TEST_RUNNER_PATH env variable.
> fix: passing runner args in CLI

- .changeset/dirty-buses-taste.md
- packages/measure/src/measure-renders.tsx
- packages/measure/src/polyfills.ts
- packages/measure/src/polyfils.ts
Improves `measureRenders` precision from whole miliseconds to microseconds by providing a better `performance.now` polyfil. React Native Jest preset provides `Date.now()` as a `performance.now()` polyfil, but that one has milisecond precision.
This issues does not occur when testing React DOM.
Resolves #516
> feat: improve `measureRenders` precision

- packages/compare/src/compare.ts
Modify min duration threshold for significant changes from absolute 4ms to relative 5% difference. Results from #534 significantly improving measurement precision.
> refactor: use % threshold for duration diff

- .changeset/popular-seahorses-provide.md
- README.md
- docusaurus/docs/api.md
- packages/compare/src/type-schemas.ts
- packages/measure/src/__tests__/measure-function.test.tsx
- packages/measure/src/index.ts
- packages/measure/src/measure-async-function.tsx
- packages/measure/src/measure-helpers.tsx
- packages/measure/src/types.ts
- packages/reassure/README.md
- packages/reassure/src/index.ts
- test-apps/native/src/fib.perf.tsx
This PR adds the `measureAsyncFunction` function, which enable consumers to measure the performance of async functions.
Unit tests were added to cover this change.
> feat: add `measureAsyncFunction` function

- .changeset/purple-jokes-rhyme.md
- .changeset/violet-hornets-call.md
- README.md
- docusaurus/docs/api.md
- packages/measure/CHANGELOG.md
- packages/measure/src/__tests__/measure-async-function.test.tsx
- packages/measure/src/__tests__/measure-renders.test.tsx
- packages/measure/src/config.ts
- packages/measure/src/measure-async-function.tsx
- packages/measure/src/measure-function.tsx
- packages/measure/src/measure-helpers.tsx
- packages/measure/src/measure-renders.tsx
- packages/reassure/README.md
- test-apps/native/jestSetup.js
Scope:
- enable outlier removal by defaults
- rename `dropOutliers` to `removeOutliers`
> feat: enable remove outliers by default

- .changeset/silent-cups-fail.md
- README.md
- docusaurus/docs/api.md
- packages/measure/src/__tests__/measure-async-function.test.tsx
- packages/measure/src/__tests__/measure-function.test.tsx
- packages/measure/src/__tests__/measure-renders.test.tsx
- packages/measure/src/measure-async-function.tsx
- packages/measure/src/measure-function.tsx
- packages/measure/src/measure-renders.tsx
- packages/reassure/README.md
This PR adds the `beforeEachRun` and `afterEachRun` options for `measureFunction`, `measureAsyncFunction` and `measureRenders` functions, allowing to specify setup/cleanup functions during each test run.
Unit tests were added to cover this feature.
> feat: add support for setup/cleanup functions during each test run

- .github/actions/setup-deps/action.yml
- .github/workflows/docs.yml
- .github/workflows/main.yml
- .github/workflows/stability.yml
actions/checkout@v4
https://github.com/actions/checkout/releases/tag/v4
https://github.com/actions/checkout/commit/11bd71901bbe5b1630ceea73d27597364c9af683
actions/setup-node@v4
https://github.com/actions/setup-node/releases/tag/v4
https://github.com/actions/setup-node/commit/49933ea5288caeca8642d1e84afbd3f7d6820020
peaceiris/actions-gh-pages@v3
https://github.com/peaceiris/actions-gh-pages/releases/tag/v3
https://github.com/peaceiris/actions-gh-pages/commit/373f7f263a76c20808c831209c920827a82a2847
> Use commit SHA instead of tags in GH actions
