callstack/reassure

.changeset/friendly-masks-suffer.md, .changeset/grumpy-snakes-nail.md, packages/reassure-cli/CHANGELOG.md, packages/reassure-cli/package.json, packages/reassure-cli/src/commands/measure.ts, packages/reassure-compare/CHANGELOG.md, packages/reassure-compare/package.json, packages/reassure-measure/CHANGELOG.md, packages/reassure-measure/package.json, packages/reassure/CHANGELOG.md, packages/reassure/package.json, packages/reassure/src/index.ts
Only affecting internal packages that are not user facing.
=> Move internal packages to @callstack scope for simpler maintenance

.changeset/shy-bugs-smoke.md, packages/reassure-measure/package.json, packages/reassure-measure/src/config.ts, packages/reassure-measure/src/measure.tsx
First step toward supporting React / RTL testing . Ability to provide custom `render` & `cleanup` function. Old code should work the same due to `render` & `cleanup` auto-discovery (from RNTL).
All tests pass.
=> refactor: allow custom render and cleanup functions

.husky/commit-msg, CONTRIBUTING.md, package.json, yarn.lock
=> Remove commitlint

.github/workflows/test-example-apps.yml
Runs perf tests in example apps.
=> chore: test example apps

.github/workflows/main.yml, .github/workflows/stability.yml, .github/workflows/test-example-apps.yml, packages/reassure-cli/package.json
Another attempt to fix failing tests on CI.
All checks fail.
=> fix: update cache setup

.github/workflows/main.yml, examples/native-expo/src/SlowList.perf-test.tsx, examples/native/src/OtherTest.perf-test.tsx, examples/native/src/SlowList.perf-test.tsx, examples/web-vite/src/SlowList.perf-test.tsx
Speed up test runs by
- merging main.yml jobs with duplicated steps.
- reduce setTimeout durations from 50 to 10 ms
All checks should pass.
=> refactor: speed up tests

.github/workflows/main.yml, .github/workflows/stability.yml, .github/workflows/test-example-apps.yml, package.json, yarn.lock
Seems like we had some redundant/useless caching code, as we implemented both high-level node caching [`actions/setup-node`](https://github.com/actions/setup-node) and low-level general caching [`actions/cache`](https://github.com/actions/cache/blob/main/examples.md#node---yarn).
All checks pass.
=> chore: cleanup and update cache settings

examples/native-expo/package.json, examples/native-expo/yarn.lock
Update deps for `examples/native-expo`
=> chore: update example/native-expo deps

examples/native-expo/package.json, examples/native-expo/yarn.lock, examples/web-vite/package.json, examples/web-vite/yarn.lock
Update reassure deps in example apps.
=> chore: update example deps

packages/reassure/README.md
=> chore: delete note about missing web support

docusaurus/docs/examples.md
=> docs: add examples

README.md, docusaurus/docs/api.md, packages/reassure/README.md
=> docs: add example usage to API

.changeset/chatty-islands-sparkle.md, README.md, docusaurus/docs/api.md, packages/reassure-cli/src/commands/measure.ts, packages/reassure/README.md
PR for issue #255 
You can test it by running `yarn reassure` in windows in an example project
=> fix: default TEST_RUNNER_PATH windows

README.md
It would be cool to have a place to link people to external resources where they can learn about Reassure. As a first resource I've added our Ultimate Guide to React Native Optimization that's released today! :)
none, it's docs
=> Add external references section to README

yarn.lock
`yarn upgrade`
All tests should pass.
=> chore(dev-deps): yarn upgrade 2023-03-06

examples/native/package.json, package.json, yarn.lock
* upgrade RNTL to v12
* upgrade RN to 0.71.4
* run yarn upgrade
All checks should pass.
=> chore: upgrade deps 2023-03-16

.github/workflows/main.yml, package.json, packages/reassure-compare/babel.config.js, packages/reassure-compare/jest.config.js, packages/reassure-compare/package.json, packages/reassure-logger/package.json, packages/reassure-measure/babel.config.js, packages/reassure-measure/jest-setup.ts, packages/reassure-measure/jest.config.js, packages/reassure-measure/package.json, packages/reassure-measure/src/__tests__/measure.test.tsx, packages/reassure-measure/src/measure.tsx, packages/reassure-measure/src/output.ts, turbo.json, yarn.lock
Scope:
All checks should pass.
=> chore: unit tests measure

README.md, packages/reassure/README.md
Add GH pages link to the README file.
Link should work.
=> docs: add gh pages link

yarn.lock
`yarn upgrade`
Standard checks should pass.
=> chore: deps upgrade 2023-04-21

README.md
Fix typos and improve grammar in README.md.
I am happy to make any changes if something is not like it's preferred 🤛
=> Fix typos and improve grammar in README.md

packages/reassure-measure/src/__tests__/measure-function.test.tsx, packages/reassure-measure/src/__tests__/measure-render.test.tsx, packages/reassure-measure/src/measure-function.tsx, packages/reassure-measure/src/measure-render.tsx, packages/reassure-measure/src/output.ts
=> refactor: small fixes

.changeset/many-cups-protect.md, packages/reassure-cli/src/commands/init.ts, packages/reassure-cli/src/commands/measure.ts, packages/reassure-cli/src/utils/git.ts, packages/reassure-cli/src/utils/logger.ts, packages/reassure-compare/src/output/console.ts, packages/reassure-compare/src/output/json.ts, packages/reassure-compare/src/output/markdown.ts, packages/reassure-compare/src/utils/logs.ts, packages/reassure-logger/src/index.ts, packages/reassure-measure/src/measure-renders.tsx, packages/reassure-measure/src/output.ts, packages/reassure-measure/src/testing-library.ts, yarn.lock
Simplify `reassure-logger` package exports
=> refactor: cleanup logger exports

README.md, docusaurus/docs/api.md, docusaurus/docs/installation.md, packages/reassure/README.md
=> docs: revert docs changes regarding measureRenders rename

docusaurus/package.json, docusaurus/yarn.lock
=> chore: upgrade docusaurus

packages/measure/package.json, packages/measure/src/__tests__/measure-function.test.tsx, packages/measure/src/__tests__/measure-renders.test.tsx
=> chore: fix local test runs due to ansi output

docusaurus/docs/installation.md, docusaurus/docs/migration-v1.md
=> docs: v1 migration guide

.github/workflows/main.yml, package.json, yarn.lock
=> chore: check deps consistency

packages/cli/package.json, packages/compare/package.json, packages/danger/package.json, packages/logger/package.json, packages/measure/package.json, packages/reassure/package.json, yarn.lock
=> chore: updata other deps

README.md, docusaurus/docs/installation.md, packages/cli/src/templates/reassure-tests, test-apps/native/reassure-tests.sh
Tweak GH workflow to measure against target branch instead of hardcoded `main`.
=> chore: tweak workflow

README.md, docusaurus/docs/examples.md, docusaurus/docs/installation.md, packages/reassure/README.md
=> docs: update readmes

.changeset/ten-toes-turn.md, packages/compare/src/index.ts, packages/compare/src/output/markdown.ts, packages/compare/src/type-schemas.ts, packages/compare/src/types.ts, packages/reassure/src/index.ts
=> feat: expose more in markdown details

.changeset/slow-carpets-smash.md, package.json, packages/cli/package.json, packages/compare/package.json, packages/danger/package.json, packages/logger/package.json, packages/measure/package.json, packages/reassure/package.json, test-apps/native/package.json, yarn.lock
=> chore: update deps 2024-07-30

package.json, yarn.lock
=> chore: update yarn to 4.4.1

.changeset/thirty-steaks-sit.md, packages/cli/src/commands/measure.ts, packages/logger/src/colors.ts
Resolves #508 
Manual testing.
=> feat: --testRegex CLI option

packages/measure/src/measure-renders.tsx
=> refactor: remove unused code

packages/compare/src/utils/__tests__/format.test.ts, packages/compare/src/utils/format.ts
=> fix: format count in markdown report

.changeset/soft-sheep-provide.md, packages/compare/package.json, packages/compare/src/output/markdown.ts, test-apps/native/src/OtherTest.perf.tsx, test-apps/native/src/fib.perf.tsx, yarn.lock
Fix case when markdown chars (e.g. backticks) in test name triggered issues in generated output.
Visual check output report.
=> fix: test name markdown escaping

.github/actions/setup-deps/action.yml, .github/workflows/main.yml, package.json
=> chore: optimise CI

.changeset/legal-colts-invent.md, packages/compare/src/output/markdown.ts
=> chore: tweak markdown output
